### ISSUE TITLE
example params

### ISSUE THREAD

**Issue by kyllker** [clovaai/AdamP#11]
What is the most simple example of params in "optimizer = AdamP(params, lr=0.001, betas=(0.9, 0.999), weight_decay=1e-2)"?

**Comment by SanghyukChun** [comment]
It is literally parameters to be updated. If you are not familiar with PyTorch, please read the following tutorial code:
https://github.com/pytorch/tutorials/blob/master/beginner_source/blitz/cifar10_tutorial.py#L156

**Comment by SanghyukChun** [comment]
Closing the issue, assuming the answer resolves the problem.
Please re-open the issue as necessary.
