### ISSUE TITLE
Experiment of Adam with warm up?

### ISSUE THREAD

**Issue by wotulong** [clovaai/AdamP#2]
Thanks for your job, can AdamP work with warm up and can warm up make AdamP works better? thks.

**Comment by bhheo** [comment]
Hi, thank you for your interest in our work.

We tested AdamP with [RAdam](https://github.com/LiyuanLucasLiu/RAdam) which makes warm-up effect on Adam optimizer.
The result was similar to original AdamP.

So, I think AdamP can work with warm-up. But, I'm not sure whether it makes improvement.
Perhaps it depends on the learning parameters or early learning instability.

**Comment by wotulong** [comment]
> Hi, thank you for your interest in our work.
> 
> We tested AdamP with [RAdam](https://github.com/LiyuanLucasLiu/RAdam) which makes warm-up effect on Adam optimizer.
> The result was similar to original AdamP.
> 
> So, I think AdamP can work with warm-up. But, I'm not sure whether it makes improvement.
> Perhaps it depends on the learning parameters or early learning instability.

Thanks for your reply. It's just what I want to know.
