### ISSUE TITLE
Question about eq (5) in section 2.3

### ISSUE THREAD

**Issue by RRoundTable** [clovaai/AdamP#4]
I appreciate for your work!

I have a question about eq (5) in section 2.3.

![image](https://user-images.githubusercontent.com/27891090/86099188-20997000-baf2-11ea-86c3-f9b418c817ee.png)

Please, give me an explanation about why w_{t+1} - w_t = \delta w_t, in most right term.

**Comment by SanghyukChun** [comment]
@RRoundTable 
It is our mistake. `\| \delta w_{t+1} \|` is correct. We will revise the paper in the next revision.
Thanks for the question!
