### ISSUE TITLE
Runtime: Adam vs AdamP

### ISSUE THREAD

**Issue by adityac8** [clovaai/AdamP#9]
Hi,
Thank you for the code release.
I am trying to run [MIRNet](https://github.com/swz30/MIRNet) by changing `Adam` to `AdamP`.
However, the training time per epoch is increased by nearly 2 times.
Is there any way to make it faster?

I tried with two environments `Python 3.7, Pytorch 1.1, CUDA 9.0` and `Python 3.7, Pytorch 1.4, CUDA 10.0` but both give the same speed.

Thanks

**Comment by bhheo** [comment]
Hi

Thank you for your interest in our work.

In our experiment , we use batch-size `256` and `AdamP` costs 8% training time than `Adam`.
MIRNet's batch-size is `16`, which is a much smaller value than our setting.
It seems to be the cause of slow processing.
So, I recommend increasing the batch-size to improve the speed.
As the batch-size increases, the ratio of the optimizer operation in training decreases, and the training time per epoch can be reduced.

I know that increasing the batch-size is often infeasible and not a good solution.
But, I don't have any other solution besides that.
`AdamP` uses additional computation for the projection operation, which is an inevitable factor.
There may be ways to further optimize the projection operation, but I couldn't found it.

**Comment by adityac8** [comment]
Thank you for a quick response.
